name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup git configuration
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Release snapshot with Maven
        run: |
          mvn --batch-mode release:prepare  -DpreparationGoals=clean -DgenerateBackupPoms=false
          mvn --batch-mode release:perform  -DpreparationGoals=clean -Ddockerfile.push
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
